### PR TITLE
docs: add troubleshooting section

### PR DESCRIPTION
**Pull request by manekinekko**

### CODE REVIEW

**Review by tom-doerr — APPROVED** [review]
Thank you for taking the time to write this!

**Comment by tom-doerr** [comment]
It's weird that you had to change the path of the plugins folder. 
Could you run
```
echo $ZSH_CUSTOM
```
to check what the location of your custom folder is?

**Comment by tom-doerr** [comment]
Did you mean to write `~/.oh-my-zsh/plugins/` to `~/.oh-my-zsh/custom/plugins/`?

**Comment by manekinekko** [comment]
> It's weird that you had to change the path of the plugins folder.
> Could you run
> 
> ```
> echo $ZSH_CUSTOM
> ```
> 
> to check what the location of your custom folder is?

It's showing me my custom plugins folders: `/Users/wassimchegham/.oh-my-zsh/custom`

**Pull request merged**
